# Generated by Django 5.1 on 2025-11-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GemilangProduct",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=500)),
                ("price", models.IntegerField()),
                ("unit", models.CharField(max_length=50)),
                ("category", models.CharField(max_length=100)),
                ("url", models.CharField(max_length=1000)),
                ("location", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "db_table": "gemilang_products",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="JuraganMaterialProduct",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=500)),
                ("price", models.IntegerField()),
                ("unit", models.CharField(max_length=50)),
                ("category", models.CharField(max_length=100)),
                ("url", models.CharField(max_length=1000)),
                ("location", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "db_table": "juragan_material_products",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Mitra10Product",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=500)),
                ("price", models.IntegerField()),
                ("unit", models.CharField(max_length=50)),
                ("category", models.CharField(max_length=100)),
                ("url", models.CharField(max_length=1000)),
                ("location", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "db_table": "mitra10_products",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TokopediaProduct",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=500)),
                ("price", models.IntegerField()),
                ("unit", models.CharField(max_length=50)),
                ("category", models.CharField(max_length=100)),
                ("url", models.CharField(max_length=1000)),
                ("location", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "db_table": "tokopedia_products",
                "managed": False,
            },
        ),
    ]
