# Generated by Django 5.1.2 on 2025-10-21 08:55

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_weight', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'cw_jobs',
            },
        ),
        migrations.CreateModel(
            name='TestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('weight_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cost_weight.testjob')),
            ],
            options={
                'db_table': 'cw_items',
            },
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
