# Generated by Django 5.2.6 on 2025-10-22 12:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_weight', '0002_testjob_testitem_delete_item_delete_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='testitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=10),
        ),
        migrations.AddField(
            model_name='testitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='testjob',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='testjob',
            name='excel_file',
            field=models.FileField(blank=True, null=True, upload_to='rab_excel/'),
        ),
        migrations.AddField(
            model_name='testjob',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18),
        ),
    ]
