# Generated by Django 5.1.4 on 2025-11-23 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_weight', '0003_testitem_quantity_testitem_unit_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testitem',
            name='ahsp_code',
            field=models.CharField(blank=True, help_text='Matched AHSP code', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testitem',
            name='ahsp_match_confidence',
            field=models.FloatField(blank=True, help_text='Match confidence score (0.0-1.0)', null=True),
        ),
        migrations.AddField(
            model_name='testitem',
            name='ahsp_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Reference price from AHSP', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='testitem',
            name='in_ahsp',
            field=models.BooleanField(default=False, help_text='Whether item was found in AHSP database'),
        ),
    ]
