"""
Django settings for AutomaticRAB project.
Generated by 'django-admin startproject' using Django 5.2.6.
"""

from pathlib import Path
import os
import sys
from dotenv import load_dotenv

# Load environment variables from .env file (if present)
load_dotenv()

# Paths
BASE_DIR = Path(__file__).resolve().parent.parent

# Core

# IMPORTANT: provide a safe default so tests/dev don't crash if .env is missing
import secrets
SECRET_KEY = os.getenv("SECRET_KEY") or "dev-" + secrets.token_urlsafe(32)

# Toggle with env; default True for ease of local dev
DEBUG = (os.getenv("DEBUG", "true").lower() == "true")

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "controversial-annmarie-izzydharma-9d67c1b0.koyeb.app",
]


# App definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # third-party
    "rest_framework",

    # project apps
    "excel_parser",
    "pdf_parser",
    "automatic_job_matching",
    "rencanakan_core",
    "cost_weight.apps.CostWeightConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "AutomaticRAB.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "AutomaticRAB.wsgi.application"

# Database
# - Uses SQLite automatically under tests or if DB_ENGINE=sqlite
# - Otherwise uses MySQL from .env
RUNNING_TESTS = any(arg in sys.argv for arg in ["test", "pytest", "py.test"])
DB_ENGINE = os.getenv("DB_ENGINE", "mysql").lower()

use_sqlite = RUNNING_TESTS or DB_ENGINE == "sqlite"

if use_sqlite:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.mysql",
            "NAME": os.getenv("MYSQL_NAME", ""),
            "USER": os.getenv("MYSQL_USER", ""),
            "PASSWORD": os.getenv("MYSQL_PASSWORD", ""),
            "HOST": os.getenv("MYSQL_HOST", "127.0.0.1"),
            "PORT": os.getenv("MYSQL_PORT", "3306"),
            # Optional: better MySQL defaults for Django
            "OPTIONS": {
                "charset": "utf8mb4",
                "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
            },
        }
    }

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# Internationalization
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# Static files
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

STATICFILES_DIRS = [
    BASE_DIR / "excel_parser" / "static",
]

# WhiteNoise storage:
if RUNNING_TESTS:
    STORAGES = {
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
else:
    STORAGES = {
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }

# Logging (console)
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {"console": {"class": "logging.StreamHandler"}},
    "root": {"handlers": ["console"], "level": "DEBUG"},
}

COST_WEIGHT_ITEM_MODEL = "rencanakan_core.RabItem"
COST_WEIGHT_JOB_MODEL  = "rencanakan_core.Rab"
COST_WEIGHT_ITEM_COST_FIELD   = "cost"
COST_WEIGHT_ITEM_WEIGHT_FIELD = "weight_pct"
COST_WEIGHT_ITEM_FK_TO_JOB    = "rab"   