# Generated by Django 5.2.6 on 2025-09-17 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(help_text='The overarching program name', max_length=255)),
                ('kegiatan', models.CharField(help_text='The specific activity within the program', max_length=255)),
                ('pekerjaan', models.CharField(help_text='The detailed name of the job or work', max_length=255)),
                ('lokasi', models.CharField(help_text='The physical location of the project', max_length=255)),
                ('tahun_anggaran', models.PositiveIntegerField(help_text='The fiscal year of the project')),
                ('source_filename', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RabEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('SITE', 'Site Header'), ('SECTION', 'Section'), ('SUB_SECTION', 'Sub-Section'), ('ITEM', 'Work Item'), ('SUB_TOTAL', 'Sub Total'), ('GRAND_TOTAL', 'Grand Total')], help_text='The classification of this row (e.g., Section, Work Item, Sub Total)', max_length=20)),
                ('item_number', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField()),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('analysis_code', models.CharField(blank=True, max_length=50, null=True)),
                ('volume', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('total_price_in_words', models.TextField(blank=True, null=True)),
                ('row_index', models.PositiveIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='excel_parser.rabentry')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='excel_parser.project')),
            ],
            options={
                'verbose_name_plural': 'RAB Entries',
                'ordering': ['id'],
            },
        ),
    ]
