# Generated by Django 5.1.2 on 2025-09-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RABItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField()),
                ('volume', models.DecimalField(decimal_places=4, max_digits=20)),
                ('unit', models.CharField(max_length=50)),
                ('source_filename', models.CharField(blank=True, max_length=255)),
                ('row_index', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['source_filename'], name='excel_parse_source__b0df63_idx')],
            },
        ),
    ]
