# Generated by Django 5.2.6 on 2025-09-24 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ahs',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('reference_group_id', models.BigIntegerField(null=True)),
                ('code', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=500, null=True)),
            ],
            options={
                'db_table': 'ahs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AhsItem',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('coefficient', models.FloatField(default=0)),
                ('section', models.CharField(max_length=20)),
                ('ahs_itemable_id', models.CharField(max_length=255)),
                ('ahs_itemable_type', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ahs_items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomAhs',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=500)),
                ('project_id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'custom_ahs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomAhsItem',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('coefficient', models.FloatField(default=0)),
                ('section', models.CharField(max_length=20)),
                ('custom_ahs_itemable_id', models.CharField(max_length=255)),
                ('custom_ahs_itemable_type', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'custom_ahs_items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemPrice',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('item_price_group_id', models.BigIntegerField(null=True)),
                ('type', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'item_prices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'projects',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rab',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('project_id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'rabs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RabItem',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500, null=True)),
                ('custom_ahs_id', models.BigIntegerField(null=True)),
                ('volume', models.FloatField(null=True)),
                ('price', models.FloatField(null=True)),
                ('profit_margin', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'rab_items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RabItemHeader',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'rab_item_headers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'units',
                'managed': False,
            },
        ),
    ]
