# Generated by Django 5.2.6 on 2025-12-01 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnmatchedAhsEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('ahs_code', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'unmatched_ahs_entries',
                'indexes': [models.Index(fields=['created_at'], name='unmatched_a_created_d9e3ec_idx')],
            },
        ),
    ]
